micronaut:
  application:
    name: ${APPNAME}
  router:
    versioning:
      enabled: true
      default-version: 1
      parameter:
        enabled: true
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
      static-resources:
        swagger:
          paths: classpath:META-INF/swagger
          mapping: /${micronaut.context-path}/swagger/**
        swagger-ui:
          paths: classpath:META-INF/swagger/views/swagger-ui
          mapping: /${micronaut.context-path}/swagger-ui/**

log:
  application:
    name: ${APPNAME}

transaction-balance:
  path: ${PATHSERVICE}

  # SE DEBEN DEFINIR LAS SIGUIENTES VARIABLES DE ENTORNO (NUNCA QUEMAR CONFIGURACIONES)

  #APPNAME=retrive-transaction;PATHSERVICE=https://twilight-cherry-1035.getsandbox.com;